// Copyright 2025 Rishit Sharma
// Licensed under the Apache License, Version 2.0
#ifndef THOR_H
#define THOR_H
#include <cstdint>
#include <vector>
#include <iostream>
#include <unordered_map>
#include<queue>
#include <algorithm>
#include <ctime>

const uint32_t BROADCAST_ID = 0xFFFFFFFF;

struct THORConfig{                // Configurations before running the protocol
    uint32_t PermId;        // Current device Permanent ID
    uint32_t TempId;        // Temporary ID generated by protocol with masked internet information
    bool myInternet;
    uint16_t attMtu;          // negotiated MTU (e.g., 185)
    uint16_t maxPayload;      // computed = attMtu - attOverhead - headerSize
    uint8_t deviceType;       // 0 -> Android, 1-> ESP32, Remaining bits for specialized devices that can be compatible wiht this protocol
    uint16_t fragPayloadSize; // how much data per fragment (<= maxPayload)
    uint16_t maxFragments;    // safety cap to avoid memory blowup
};

static constexpr uint16_t headerSize  = 22;
static constexpr uint16_t attOverhead = 3;
static constexpr uint16_t SAFE_MTU_CAP  = 185; // ESP32 safe cap

#pragma pack(push, 1)

enum class THORPacketType : uint8_t {
    HELLO = 1,
    ACK   = 2,
    DATA  = 3
};

struct flags{
    unsigned char ttl : 5;// time to live
    unsigned char intneighbour : 1;// 1 = neighbour has internet, 0 = no internet neighbour.
    unsigned char visited : 1;//1 = visited, 0 = not visited
    // Context-dependent flag moreData:
// DATA  -> continuation
// ACK   -> success
    unsigned char moreData : 1; 
};

struct Header {
    THORPacketType type;   // 1 byte

    flags  flagsAndTTL;  // 1 byte (Renamed from 'ttl')
    uint32_t destinationId;// 4 bytes
    uint32_t senderId;     // 4 bytes
    uint32_t originId;     // 4 bytes
    uint32_t nextHopId;    // 4 bytes
    uint32_t sequence;     // 4 bytes
};//total : 22 bytes
#pragma pack(pop)

struct Packet {
    Header header;
    std::vector<uint8_t> payload;
};
struct NeighborInfo {
    time_t lastSeen;          // To expire old neighbors
    int    rssi;              // Signal strength
    bool hasInternetDirect;   // Priority 1 (Bit 7 of Header)
    bool hasInternetIndirect; // Priority 2 (Bit 5 of Header)
    bool isVisited;           // Priority 3 (Bit 6 of Header) - Avoid if true
    bool lock;                //To lock the specific route, can only lock 2 nodes in the table
};
static_assert(sizeof(Header) == 22, "Error: Header size must be exactly 22 bytes for BLE!");

#pragma pack(push, 1)
struct fragmentedHeader
{
    uint32_t OriginId;
    unsigned char sequence : 1;
    unsigned char moreData : 1;
};// Total bytes = 5 bytes
#pragma pack(pop)

struct fragmentedPacket {
    fragmentedHeader fheader;
    std::vector<uint8_t> fpayload;
};//allowed = 6 bytes + 26 bytes payload

struct OutHeader
{
    uint32_t SenderId;
    uint32_t DestId;
    uint32_t OriginId;
    uint32_t sequence;
};

class THOR
{
public:
    THORConfig cfg;
    THOR(const THORConfig& c) : cfg(c) {InitConfig();}
    void InitConfig();
    uint32_t ParseTempId();
    std::vector<uint8_t> Serialize(const Packet& packet);
    bool Deserialize(const std::vector<uint8_t>& data, Packet& outPacket);
    bool DeserializeHeader(const std::vector<uint8_t>& data, Header& outheader);
    std::vector<uint8_t> SerializeHeader(const Header& header);
    std::vector<uint8_t> CreateHello(uint32_t DestId ,uint32_t SenderId, uint32_t OriginId, uint32_t Sequence);
    bool HandleHello(const std::vector<uint8_t>& data);
    std::vector<uint8_t> ACK(uint32_t MyId,bool intneighbour);
    bool HandleAck(const std::vector<uint8_t>& data);
    std::vector<uint8_t> SendPacket(uint32_t DestId, uint32_t SenderId, uint32_t OriginId, uint32_t Sequence, const std::vector<uint8_t>& payload);
    std::vector<uint8_t> HandleData(const std::vector<uint8_t>& data, Packet& outPacket, uint32_t MyNodeId); 
    void RemoveOld();
    uint32_t GetBestNextHop();
    std::vector<std::vector<uint8_t>> ProcessQueue(); //Android Wrapper Endpoint Function
    
private:
    uint32_t CreateTempId();
    std::vector<uint8_t> CreateACK(uint32_t DestId, uint32_t SenderId,uint32_t OriginId,uint32_t NextHopId,uint32_t Sequence, bool intneighbour,bool successACK);
    void ProcessACK(Header outheader);
    std::unordered_map<uint32_t, NeighborInfo> neighborTable;
    std::queue <OutHeader> outheaderFields;
    std::vector<Packet> packetQueue;
    bool transaction = false;
};

#endif /* THOR_H */
